AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ScanResultTopicARN:
    Type: String
    Description: The ARN of the scan result SNS topic in storage stack.
  AWSACCOUNTNO:
    Type: Number
    Description: Provide AWS Account ID.
  AWSSecurityHubARN:
    Type: String
    Description: Provide AWS Security hub ARN from selected region

Resources:
  C1FSecurityHub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucket-4716/lambda.zip
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          ACCOUNT_ID: !Ref AWSACCOUNTNO
          SECURITY_HUB_ARN: !Ref AWSSecurityHubARN
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - securityhub:*
            Resource:
              - !Ref AWSSecurityHubARN
          
      Events:
        ScanResult:
          Type: SNS
          Properties:
            Topic: !Ref ScanResultTopicARN
